# Generated by Django 3.2.18 on 2023-02-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='counrty',
            new_name='country',
        ),
    ]
