# Generated by Django 3.2.18 on 2023-03-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_retailaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='retailer',
            field=models.BooleanField(default=False),
        ),
    ]
