# Generated by Django 3.2.18 on 2023-03-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_useraccount_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='retailer_requested',
            field=models.BooleanField(default=False),
        ),
    ]
