# Generated by Django 3.2.18 on 2023-03-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='product_seller',
            field=models.CharField(default='', editable=False, max_length=254),
        ),
    ]
