# Generated by Django 3.2.18 on 2023-03-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orderlineitem_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_account',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
