# Generated by Django 3.2.18 on 2023-05-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_request',
            field=models.BooleanField(default=False),
        ),
    ]
