# Generated by Django 3.2.18 on 2023-05-29 15:11

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_retailaccount_cancel_subscription'),
        ('checkout', '0004_order_cancel_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('street_address1', models.CharField(max_length=254)),
                ('street_address2', models.CharField(blank=True, max_length=254, null=True)),
                ('postcode', models.CharField(max_length=20)),
                ('town_or_city', models.CharField(max_length=100)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.useraccount')),
            ],
        ),
    ]
